AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Speech-to-text telegram bot
Globals:
  Function:
    Timeout: 3
    Runtime: python3.9
    Architectures:
      - arm64

Resources:
  PTBFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: main.lambda_handler
      FunctionUrlConfig:
        AuthType: NONE

Outputs:
  TelegramApi:
    Description: "Lambda URL for PTB function"
    Value:
      Fn::GetAtt: PTBFunctionUrl.FunctionUrl
